# Generated by Django 3.1.3 on 2022-03-19 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stid', models.IntegerField()),
                ('stname', models.CharField(max_length=70)),
                ('stemail', models.EmailField(max_length=70)),
                ('stpass', models.CharField(max_length=70)),
            ],
        ),
    ]
